server.port=8081

spring.security.oauth2.client.provider.external.issuer-uri=http://localhost:8080/realms/study_spring_keycloak1

spring.security.oauth2.client.registration.external.provider=external
spring.security.oauth2.client.registration.external.client-name=spring_oath2_keycloak_study1
spring.security.oauth2.client.registration.external.client-id=spring_oath2_keycloak_study1
spring.security.oauth2.client.registration.external.client-secret=HWHCsRvUVmHot2Oih6SBLDLIF9oFsg9t
spring.security.oauth2.client.registration.external.scope=openid,offline_access,profile
spring.security.oauth2.client.registration.external.authorization-grant-type=authorization_code